/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class DesimalToBiner extends javax.swing.JFrame {

    /**
     * Creates new form DesimalToBiner
     */
    public DesimalToBiner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBiner = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDesimal = new javax.swing.JTextField();
        btnKonversi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\b91960_0.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESIMAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 80, 30);
        getContentPane().add(txtBiner);
        txtBiner.setBounds(340, 210, 110, 30);

        btnConvert.setBackground(new java.awt.Color(204, 204, 204));
        btnConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConvert.setText("<=>");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvert);
        btnConvert.setBounds(190, 210, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BINER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 170, 60, 30);

        txtDesimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesimalActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesimal);
        txtDesimal.setBounds(10, 210, 110, 30);

        btnKonversi.setText("KONVERSI");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKonversi);
        btnKonversi.setBounds(60, 330, 360, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KONVERSI BILANGAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 60, 240, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\7248760-05-0-1476716450-1476716460-0-1476943441-0-1476960808-1476960812-650-9ef4c38e4c-1-1477035084.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-90, -20, 740, 480);

        setBounds(0, 0, 480, 467);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        if(btnConvert.getText().equals("Convet")){
            btnConvert.setText("Convert");
        } else {
            btnConvert.setText("Convert");
        }
       
        if(btnConvert.getText().equals("COnvert")){
            txtBiner.setEnabled(false);
            txtBiner.setText("");
            txtDesimal.setEnabled(true);
        } else {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(false);
            txtDesimal.setText("");
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        try {   
           
            if(txtBiner.getText().isEmpty()){
                int desi = Integer.valueOf(txtDesimal.getText());
                // konversi ke biner
                String bin = Integer.toBinaryString(desi);
                txtBiner.setText(bin);
            } else {
                String biner = txtBiner.getText();
                // konversi ke desimal
                int des = Integer.parseInt(biner, 2);
                txtDesimal.setText(String.valueOf(des));
            }

           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input tidak valid:  "+ e.getMessage());
        } finally {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(true);
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtDesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesimalToBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesimalToBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesimalToBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesimalToBiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesimalToBiner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBiner;
    private javax.swing.JTextField txtDesimal;
    // End of variables declaration//GEN-END:variables
}
